# DESARROLLO
version: "3.4"

services:

  web:
    image: dinotomassini/php7.4.16-mysqli-apache:php7.4-mysqli
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ../../backend:/var/www/html
    env_file:
      - .env
#    links:
#      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 33306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./init/crearBD.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./data/init/llenarDatos.sql:docker-entrypint-initdb.d/llenarDatos.sql
    env_file:
      - ../../backend/.env
    # restart: always
